name: Publish Package

on: 
  release:
    tags:
      - release-v**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Publish
      run: |
        npm i
        npm run lint
        npm run test
        npm run build
        npm publish --tag ${GITHUB_REF##*/}